// steps/selectTopic.js

// The list of topics (Cleaned: no numbers)
const topicsList = [
"CEO - Board-Ready Operating Dashboard",
"CEO - Weekly Execution Scorecard",
"CEO - Decision Bottleneck Diagnostic",
"CEO - Executive Accountability Framework",
"CEO - Strategic Initiative Kill List",
"CEO - Time Allocation Audit",
"CEO - Founder Dependency Risk Map",
"CEO - Org-Wide Priority Cascade",
"CEO - Operating Rhythm Playbook",
"CEO - Executive Effectiveness Self-Assessment",
"CEO - Single-Point-of-Failure Analysis",
"CEO - Strategy vs Reality Gap Report",
"CEO - Leadership Credibility Audit",
"CEO - Execution Drag Index",
"CEO - Company Complexity Threshold Test",
"CEO - Delegation Failure Heatmap",
"CEO - Crisis Decision Playbook",
"CEO - CEO-to-Board Communication Template",
"CEO - Internal Alignment Pulse Survey",
"CEO - Exit-Readiness Reality Check",
"CEO - Executive Decision Latency Tracker",
"CEO - Strategic Tradeoff Framework",
"CEO - CEO Succession Risk Outline",
"CEO - Capital Allocation Discipline Guide",
"CEO - Executive Focus Drift Detector",
"CFO - Rolling 13-Week Cash Forecast",
"CFO - Cash Flow Early Warning Dashboard",
"CFO - Margin Leakage Diagnostic",
"CFO - Unit Economics Stress Test",
"CFO - Forecast Accuracy Tracker",
"CFO - Board-Level Financial Narrative",
"CFO - Working Capital Optimization Model",
"CFO - Cost Structure Rationalization Map",
"CFO - Liquidity Crisis Response Plan",
"CFO - Scenario Planning Playbook",
"CFO - EBITDA Quality Bridge",
"CFO - Revenue Recognition Risk Checklist",
"CFO - Forecast Driver Sensitivity Model",
"CFO - Cost-to-Serve Analysis",
"CFO - Debt Covenant Monitoring Sheet",
"CFO - Budget Credibility Scorecard",
"CFO - Financial Close Acceleration Plan",
"CFO - Investor Reporting Readiness Checklist",
"CFO - Cash Conversion Cycle Tracker",
"CFO - Capital Raise Readiness Toolkit",
"CFO - Financial Systems Control Map",
"CFO - Data Integrity Confidence Index",
"CFO - Spend Governance Framework",
"COO - Execution Gap Heatmap",
"COO - Cross-Functional Dependency Map",
"COO - Process Ownership Matrix",
"COO - Operating Cadence Design",
"COO - KPI-to-Action Translation Sheet",
"COO - Bottleneck Identification Tool",
"COO - SLA Accountability Framework",
"COO - Operational Risk Register",
"COO - Scale Readiness Checklist",
"COO - Process Simplification Scorecard",
"COO - Throughput Constraint Analysis",
"COO - Cost Leakage Operations Audit",
"COO - Execution Consistency Index",
"COO - Operational Decision Rights Map",
"COO - Daily Management System Template",
"COO - Vendor Reliability Risk Map",
"COO - Capacity Planning Model",
"COO - Quality Failure Root Cause Tool",
"COO - Ops-to-Finance Alignment Diagnostic",
"COO - Operational Fragility Index",
"COO - Multi-Site Operations Control Sheet",
"COO - Service Level Failure Tracker",
"COO - Operational Scalability Stress Test",
"CTO - Tech Debt Risk Assessment",
"CTO - ERP Readiness Checklist",
"CTO - Systems Integration Map",
"CTO - Data Integrity Validation Tool",
"CTO - Build vs Buy Decision Framework",
"CTO - IT Spend ROI Tracker",
"CTO - Security & Access Control Audit",
"CTO - Architecture Scalability Review",
"CTO - Vendor Dependency Risk Map",
"CTO - Transformation Roadmap",
"CTO - Legacy System Triage Tool",
"CTO - SaaS Reliability Risk Dashboard",
"CTO - Engineering Velocity Reality Check",
"CTO - Data Single-Source-of-Truth Audit",
"CTO - Automation ROI Prioritization Grid",
"CTO - Tech Org Capability Heatmap",
"CTO - Cyber Incident Response Playbook",
"CTO - Product Delivery Bottleneck Map",
"CTO - Platform Stability Index",
"CTO - Technology Governance Framework",
"CTO - Infrastructure Cost Control Model",
"CTO - API Dependency Risk Tracker",
"CTO - Cloud Spend Discipline Sheet",
"CMO - CAC Payback Period Tracker",
"CMO - Funnel Conversion Integrity Audit",
"CMO - GTM Reset Playbook",
"CMO - Revenue Attribution Model",
"CMO - Channel Profitability Scorecard",
"CMO - Messaging-to-Market Fit Test",
"CMO - Growth Experiment Prioritization Grid",
"CMO - Sales-Marketing Alignment Diagnostic",
"CMO - Demand Forecast Accuracy Tracker",
"CMO - Brand Risk Exposure Map",
"CMO - Pipeline Quality Audit",
"CMO - Pricing Power Sensitivity Test",
"CMO - Customer Concentration Risk Tool",
"CMO - Market Expansion Readiness Checklist",
"CMO - Campaign ROI Kill Sheet",
"CMO - Revenue Mix Risk Dashboard",
"CMO - Brand-to-Revenue Attribution Map",
"CMO - Churn Root Cause Diagnostic",
"CMO - Growth vs Margin Tradeoff Model",
"CMO - Marketing Spend Efficiency Index",
"CMO - Customer Lifetime Value Stress Test",
"CMO - Product-Market Fit Drift Tracker",
"CMO - Demand Volatility Risk Model",
"CHRO - Leadership Gap Assessment",
"CHRO - Executive Succession Risk Matrix",
"CHRO - Incentive Alignment Model",
"CHRO - Performance Management Reset Toolkit",
"CHRO - Org Design Stress Test",
"CHRO - Culture vs Execution Diagnostic",
"CHRO - Talent Retention Risk Map",
"CHRO - Role Clarity Framework",
"CHRO - Accountability Without Burnout Guide",
"CHRO - Change Fatigue Index",
"CHRO - Leadership Bench Strength Audit",
"CHRO - Compensation Compression Risk Tool",
"CHRO - Manager Effectiveness Scorecard",
"CHRO - Hiring Mistake Cost Calculator",
"CHRO - Workforce Scalability Index",
"CHRO - Employee Flight Risk Dashboard",
"CHRO - Founder-to-Professional Org Transition Plan",
"CHRO - Incentive Leakage Diagnostic",
"CHRO - High-Performer Retention Playbook",
"CHRO - People Risk Heatmap",
"CHRO - Org Capability Maturity Model",
"CHRO - Executive Role Redundancy Review",
"Board - CEO Performance Evaluation Framework",
"Board - Strategy-to-Execution Visibility Dashboard",
"Board - Risk Oversight Heatmap",
"Board - Capital Allocation Review Tool",
"Board - Management Credibility Scorecard",
"Board - KPI Signal vs Noise Filter",
"Board - Board Pack Quality Checklist",
"Board - Scenario Downside Readiness Review",
"Board - Executive Bench Strength Map",
"Board - Governance Maturity Assessment",
"Board - CEO Dependency Risk Analysis",
"Board - Financial Transparency Scorecard",
"Board - Exit Timing Readiness Tool",
"Board - Investor Communication Consistency Audit",
"Board - Strategic Drift Detection Tool",
"Board - Portfolio Risk Summary Template",
"Board - Board Decision Effectiveness Review",
"Board - Management Team Cohesion Index",
"Board - Capital Efficiency Diagnostic",
"Board - Crisis Governance Playbook",
"Private Equity Partner - Value Creation Tracking Model",
"Private Equity Partner - 100-Day Plan Template",
"Private Equity Partner - Management Capability Diagnostic",
"Private Equity Partner - Post-Close Integration Checklist",
"Private Equity Partner - EBITDA Bridge Tracker",
"Private Equity Partner - Operational Leverage Map",
"Private Equity Partner - Risk Concentration Analysis",
"Private Equity Partner - Portfolio Company Health Index",
"Private Equity Partner - Exit Readiness Scorecard",
"Private Equity Partner - Leadership Replacement Decision Tree",
"Private Equity Partner - Cash Discipline Audit",
"Private Equity Partner - Forecast Reliability Test",
"Private Equity Partner - Cost Reduction Sustainability Model",
"Private Equity Partner - KPI Credibility Assessment",
"Private Equity Partner - Deal Thesis Drift Tracker",
"Private Equity Partner - Operating Partner Intervention Map",
"Private Equity Partner - Talent Upgrade Roadmap",
"Private Equity Partner - Synergy Realization Dashboard",
"Private Equity Partner - Value Leakage Detector",
"Private Equity Partner - Hold Period Risk Map",
"Founder - First-Time Board Management Guide",
"Founder - Letting Go Without Losing Control Framework",
"Founder - From Heroics to Systems Transition Plan",
"Founder - Founder-to-CEO Evolution Checklist",
"Founder - Delegation Failure Diagnostic",
"Founder - Scaling Leadership Blind Spots",
"Founder - Investor Expectation Reality Check",
"Founder - Founder Risk Mitigation Map",
"Founder - Personal Bottleneck Audit",
"Founder - Exit Emotional Readiness Guide",
"Founder - Founder Myth vs Reality Test",
"Founder - Founder Burnout Early Warning Signs",
"Founder - Trusting the Numbers Diagnostic",
"Founder - Leadership Identity Transition Tool",
"Founder - Founder Shadow Risk Analysis",
"Founder - Decision Fatigue Assessment",
"Founder - Founder Compensation Reality Check",
"Founder - Succession Anxiety Worksheet",
"Founder - Founder Control Relinquishment Plan",
"Founder - Founder Narrative Rewrite Framework"
];

export async function selectTopic() {
    console.log("Selecting random topic from list...");
    
    // Logic: Select Random Topic
    const randomIndex = Math.floor(Math.random() * topicsList.length);
    const selectedTopic = topicsList[randomIndex];

    return selectedTopic;
}
